### PR TITLE
fix(climate): state of climate switch not set to ON when enabled #125 #127

### LINKED ISSUE #125: Charging and Climate switches not working in 3.0.0 beta3
I'm getting problems trying some of the new switches.

Charging (I'm not quite sure what this is supposed to do, but...), when switching on:

```
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:238
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 14:13:05 (1 occurrences)
Last logged: 14:13:05

[140581630699328] 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 238, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2149, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2186, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 272, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 882, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 952, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/jlrincontrol/switch.py", line 81, in async_turn_on
    params = self.get_service_params(True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/jlrincontrol/switch.py", line 125, in get_service_params
    params = list(service.get("params"))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable
```

Climate : in the JLR app, I have the option of using either "Engine Climate" (which only works when the charge cable isn't plugged in) or "Electric Climate". If I try to use the new switch it doesn't appear to do anything (the car is currently plugged in, although I don't see any errors)

[config_entry-jlrincontrol-3a5a766573d9cc96491cf9b72151bb8c.json.txt](https://github.com/msp1974/homeassistant-jlrincontrol/files/14157312/config_entry-jlrincontrol-3a5a766573d9cc96491cf9b72151bb8c.json.txt)

### PR DESCRIPTION
**Pull request by ismarslomic**
- Separate state for Climate (engine) and Climate (electric) switches in two different state variables
- Fix state logic

Closes #125 and #127

### CODE REVIEW

**Comment by ismarslomic** [comment]
### Important note: 
when climate (engine) is activated then `"CLIMATE_STATUS_OPERATING_STATUS": "OFF"`, see [diagnostic file](https://github.com/msp1974/homeassistant-jlrincontrol/files/14158641/config_entry-jlrincontrol-3a5a766573d9cc96491cf9b72151bb8c.json.2.txt) from Liam. This will set the [Climate](https://github.com/msp1974/homeassistant-jlrincontrol/blob/dev/custom_components/jlrincontrol/sensor.py#L611) _sensor_ state to `OFF` instead of `HEATING`.

I don't see any other property we could read the climate status from. One solution could be to check if _Climate (engine)_ is activated and hardcode the value to `HEATING`, otherwise use the value from `CLIMATE_STATUS_OPERATING_STATUS`. But I guess that there are two different states `HEATING` and `COOLING`?

**Comment by ismarslomic** [comment]
@msp1974 I assume you are busy? It would be very nice to merge this as it solves two of our issues.

**Comment by msp1974** [comment]
Sorry, yes been tied up for a few days.  Fine with this and thanks for all your help on the beta issues.  Let me know when you think it is good enough to release and we can merge into master.

**Comment by ismarslomic** [comment]
@msp1974 I want to make new beta release and ask Liam to test few of the latest changes in dev before we merge to master. 

Do you have input on my note in current PR: https://github.com/msp1974/homeassistant-jlrincontrol/pull/129#issuecomment-1926519272 ?

**Comment by msp1974** [comment]
Sorry, missed that. What about if we keep it simple for now and just set it to On if we see engine climate on.  I'm not sure it is that sofisticated that it differentiates between heating and cooling.  For electric climate, we can pick up CLIMATE_STATUS_OPERATING_STATUS.

**Comment by ismarslomic** [comment]
Sounds good! I will do the change

**Pull request merged**
